language: node_js
sudo: required
before_script:
  - npm install -g web-component-tester
  - npm install -g bower polymer-cli@0.18.1
  - sudo mv /usr/bin/google-chrome /usr/bin/google-chrome-old
  - sudo mv /usr/bin/google-chrome-beta /usr/bin/google-chrome
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
script:
  - npm install
  - bower install --silent
  - xvfb-run polymer test
dist: trusty
